# Generated by Django 4.2.5 on 2023-10-05 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название урока', max_length=100, verbose_name='Название урока')),
                ('href', models.CharField(help_text='Введите ссылку на урок', max_length=100, verbose_name='Ссылка на урок')),
                ('view_duration', models.PositiveIntegerField(verbose_name='Продолжительность просмотра (секунды)')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=100, verbose_name='Название продукта')),
                ('href', models.CharField(help_text='Введите ссылку на продукт', max_length=100, verbose_name='Ссылка на продукт')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_products', to=settings.AUTH_USER_MODEL, verbose_name='Владелец продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='LessonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_time', models.DateTimeField(null=True, verbose_name='Время просмотра')),
                ('viewed', models.CharField(max_length=100, verbose_name='Статус просмотра')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_view', to='product.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр уроков',
                'verbose_name_plural': 'Просмотры уроков',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='product.product', verbose_name='Продукты'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к продуктам',
                'verbose_name_plural': 'Доступы к продуктам',
            },
        ),
    ]
